## import numpy

In [1]:
import numpy as np

## Buat Array 1D

In [2]:
a= np.array([1,2,3,4])

In [6]:
a[0],a[1],a[2],a[3]

(1, 2, 3, 4)

## Penggunaan tipe pada numpy

In [11]:
a

array([1, 2, 3, 4])

In [14]:
a.dtype

dtype('int64')

In [16]:
type(a)

numpy.ndarray

## bongkar 1D array

In [18]:
a.size

4

In [19]:
a.ndim

1

In [20]:
a.shape

(4,)

## Indexing

In [22]:
b = np.array([1,2.1,3,4,99])

In [23]:
b[0]

1.0

In [25]:
b[0]=100
b

array([100. ,   2.1,   3. ,   4. ,  99. ])

## slicing

In [26]:
b

array([100. ,   2.1,   3. ,   4. ,  99. ])

In [27]:
b[1:4] #akan ditampilkan indeks ke1 sampai 3 ==> var[awal_slicing:batas_slicing] *batas tidak termasuk

array([2.1, 3. , 4. ])

In [29]:
b[2:4]=6.5,1.5
b

array([100. ,   2.1,   6.5,   1.5,  99. ])